### ISSUE TITLE
Getting warning: "Package is-ip has been ignored"

### ISSUE THREAD

**Issue by jkoutavas** [sindresorhus/is-ip#12]
I'm getting this warning when building my React Native app:

```
warn Package is-ip has been ignored because it contains invalid configuration. Reason: Package subpath './package.json' is not defined by "exports" in /Users/jay/app/node_modules/is-ip/package.json
```

I'm using `is-ip@^4.0.0`

**Comment by sindresorhus** [comment]
That warning is invalid and the problem is React Native, not this package.

I recommend you open an issue on https://github.com/facebook/react-native/issues instead.

**Comment by jkoutavas** [comment]
> That warning is invalid and the problem is React Native, not this package.
> 
@sindresorhus can you explain why it's invalid? (It'll help me understand how to file a proper issue.) Thank you.

**Comment by sindresorhus** [comment]
Not exporting `./package.json` is not invalid configuration, it's actually common practice not to export it. React Native should not waste the time of their users and also package maintainers with this kinds of false warnings.

**Comment by jkoutavas** [comment]
> Not exporting `./package.json` is not invalid configuration, it's actually common practice not to export it. React Native should not waste the time of their users and also package maintainers with this kinds of false warnings.

Well, after using React Native for over 2-1/2 years, and dozens of NPM packages with it, this is the first one that gave this warning. Is it difficult to make this change to your package?

**Comment by JimTeva** [comment]
@jkoutavas it looks like it is react-native that should update its code (https://github.com/react-native-community/cli/issues/1168)

In the meantime I added "./package.json": "./package.json" in the exports, it removed the warning but unfortunately the lib does not seems to work well with react-native v0.65.1 (only tested "isIP").

Finally I asked chatGPT and it gave me that lol:
```
export function isIP(str: string) {
  var pattern4 =
    /^(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$/;
  var pattern6 =
    /^(([0-9a-fA-F]{1,4}:){7,7}[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,7}:|([0-9a-fA-F]{1,4}:){1,6}:[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,5}(:[0-9a-fA-F]{1,4}){1,2}|([0-9a-fA-F]{1,4}:){1,4}(:[0-9a-fA-F]{1,4}){1,3}|([0-9a-fA-F]{1,4}:){1,3}(:[0-9a-fA-F]{1,4}){1,4}|([0-9a-fA-F]{1,4}:){1,2}(:[0-9a-fA-F]{1,4}){1,5}|[0-9a-fA-F]{1,4}:((:[0-9a-fA-F]{1,4}){1,6})|:((:[0-9a-fA-F]{1,4}){1,7}|:))$/;
  return pattern4.test(str) || pattern6.test(str);
}
```
Works pretty well...
