### ISSUE TITLE
Bug browser compatibility lost with version 5.0.0

### ISSUE THREAD

**Issue by AuspeXeu** [sindresorhus/is-ip#13]
Version 4.0.0 used to work in the browser, with the  new `super-regex` dependency, this package does not work any longer.

**Comment by sindresorhus** [comment]
What exactly does not work?

**Comment by AuspeXeu** [comment]
I am building with webpack and the import won't compile any longer.

**Comment by sindresorhus** [comment]
That has nothing to do with browser compatibility. Most likely you have not adjusted your Webpack config to ESM or using a too old Webpack version.

https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c
