### ISSUE TITLE
is IPv6 not work as expected

### ISSUE THREAD

**Issue by keyndark** [sindresorhus/is-ip#4]
Hi.
Function return true for:
`isIp.v6('2a00:1450:4010:c0b::5f:8080')`

Even for:
 `isIp.v6('2a00:1450:4010:c0b::5f:8080:5555')`

**Comment by sindresorhus** [comment]
Those are valid IPv6 addresses AFAIK.

http://v6decode.com

**Comment by keyndark** [comment]
Thanks for answer. Yes your right. I`m read the docs about ipv6 address second time and now have no issue with validation.
