### ISSUE TITLE
Causes PhantomJS tests to fail

### ISSUE THREAD

**Issue by willmacdonald** [sindresorhus/is-ip#9]
While the code works as expected, it caused our PhantomJS tests to fail with the following error:

```
PhantomJS 2.1.1 (Mac OS X 0.0.0) ERROR
  SyntaxError: Unexpected token 'const'
```

node v10.21.0 (npm v6.14.8) on Mac 10.15.6

**Comment by sindresorhus** [comment]
This is a Node.js package. PhantomJS compatibility is not a concern.
